sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - source # store source code of hexo in source branch
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    all_branches: true # solve a permission problem
    target_branch: master
    local-dir: public