language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - source # store source code of hexo in source branch
script:
  - hexo generate
deploy:
  provider: pages
  token: $GH_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: source
    local_dir: public
